services:
  mysql:
    image: mysql:8.0
    container_name: recipe-mysql
    environment:
      MYSQL_DATABASE: recipedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3069:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: recipe-app
    ports:
      - "3031:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recipedb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - mysql

volumes:
  mysql-data: